### ISSUE TITLE
Contributor Workflow

### ISSUE THREAD

**Issue by srinjoyc** [onflow/developer-portal#496] opened 2022-08-02 22:44 UTC
As a contributor, when I submit any PR that changes documentation (on any supported repo):
- Notice when PRs are up, preview on staging with a feature branch 
- "central service" could spin up new routes in a staging link prefixed with `preview/commit-sha` + post message to preview. 
- Check for the rules below and provide feedback through comments. Ideally, prevent merge if rules are not met.

Rules:
(Rule) Add or remove directories/files:
- If my repo changes folder structure, the CI will look for any routing changes and force me to have redirects for them to prevent other repos of having broken links. When authors of other repos try to update, the CI should inform them of any 'redirect' links that they are using to help them update to the new ones. (Link + auditing issue).
- The CI could check for links that 404. Ideally, post a comment/issue/pr with the issue. Could be centralized via a service in the remix BE.

(Rule) Add or remove links:
- Fully qualified links for referencing outside your repo and relative links for inside your repo. https://github.com/onflow/next-docs-v1/issues/495 
- Checked for in CI for any 404s

(Rule) File names (duplicate files):
- If md and mdx file with same name, md will be loaded first. MD is given priority - to get MDX, remove MD file.
- Case is ignored for file names
- file names have to be URL friendly -> no spaces, etc.

(Rule) Don't support imports in MDX files
- Use from default list but can't use custom components.

Workflow:
- As a Cadence repo contributor, I submit a PR that changes content of some files changes a folder name.
- I should get a comment on my PR with a preview to all changes files that I can view.
- I should get a list of links that are broken (as per rules above) as a result of my folder(routing) change. And I should be forced to add a redirect for the change so that all other links that reference it continue to work.
- Once fixed, I can merge it and have it deployed instantly.

**Comment by LaurenIke** [comment] 2022-09-26 12:39
@srinjoyc can this be marked complete.  I believe it is a duplicate of work that was already completed.

**Comment by nialexsan** [comment] 2023-09-08 17:23
static builds https://github.com/onflow/docs

**Closed by nialexsan** 2023-09-08 17:23 UTC
